# Basic Neural Network Built With Numpy

In [25]:
import numpy as np

In [26]:
# Create and format inputs and outputs
# The output is equal to the first value in each input array

inputs = [[[0],[0],[1]],
          [[1],[1],[1]],
          [[1],[0],[1]],
          [[0],[1],[1]],
          [[0],[1],[0]],
          [[1],[1],[0]]]
         
outs = [[[0]],
        [[1]],
        [[1]],
        [[0]],
        [[0]],
        [[1]]]

train = []
for i,o in zip(inputs,outs):
    train.append((np.asarray(i),np.asarray(o)))

In [27]:
class Net(object):
    def __init__(self,sizes):
        # Intitialize random weights
        self.weights = [np.random.randn(r,c) for r,c in zip(sizes[1:],sizes[:-1])]
    
    def sigmoid(self,x):
        # Nonlinear function
        return 1/(1+np.exp(-x))
    
    def sigmoid_deriv(self,x):
        # Derivative of nonlinear function
        return self.sigmoid(x) * (1-self.sigmoid(x))
    
    def forward(self,a):
        # Feed forward through the network
        for w in self.weights:
            a = self.sigmoid(np.dot(w,a))
        return a
    
    def train(self,data,epochs,alpha):
        # Train the network
        for e in range(epochs):
            for x,y in data:
                a = x
                zs = []
                activations = [a]
                
                # Feedforward
                for w in self.weights:
                    # Store z vector
                    z = np.dot(w,a)
                    zs.append(z)
                    
                    # Store activation vector
                    a = self.sigmoid(z)
                    activations.append(a)
                
                # Calculate current loss
                ypred = a
                loss = ypred - y
                
                # Find the gradient of the last set of weights
                nabla_constant = (loss*2)*self.sigmoid_deriv(zs[-1])
                nabla_w = np.dot(nabla_constant,activations[-2].T)
                self.weights[-1] -= alpha*nabla_w
                
                # Work backwards through the network, finding the gradient
                # of the weights at each layer
                for i in range(2,len(w)+1):
                    nabla_constant = np.dot(self.sigmoid_deriv(zs[-i]),nabla_constant)
                    nabla_w = np.dot(nabla_constant,activations[-i-1].T)
                    self.weights[-2]-= alpha*nabla_w
                    
    def cost(self,data):
        # Calculate the current cost of the network
        cost = np.zeros(data[0][1].shape)
        for x,y in data:
            ypred = self.forward(x)
            cost += (ypred-y)**2
        return cost

In [28]:
# Initialize a three layer network
n = Net([3,10,1])

In [29]:
# Find the initial cost of the network
n.cost(train)

array([[ 1.90945771]])

In [30]:
# Train the network for 10000 epochs
n.train(train,10000,0.1)

In [31]:
# Find the cost of the network after training
n.cost(train)

array([[ 0.00463853]])

In [32]:
# Create test inputs to see how the network performs on unseen data
t0 = np.asarray([[0],[0],[0]])
t1 = np.asarray([[1],[0],[0]])

In [33]:
n.forward(t0)

array([[ 0.05306956]])

In [34]:
n.forward(t1)

array([[ 0.9939769]])